/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-01-07 02:06:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cms_005fman;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class app_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common.jsp", Long.valueOf(1411354428000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      common.DbinfoBean userbeanses = null;
      synchronized (session) {
        userbeanses = (common.DbinfoBean) _jspx_page_context.getAttribute("userbeanses", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (userbeanses == null){
          userbeanses = new common.DbinfoBean();
          _jspx_page_context.setAttribute("userbeanses", userbeanses, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>検定マスタメンテナンス</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<h2>検定マスタメンテナンス</h2>\n");
      out.write("\t<form action=\"/cms/logout\" method=\"POST\">\n");
      out.write("\t<table border=\"0\"  width=\"100%\" height=\"100%\">\n");
      out.write("\t<tr>\n");
      out.write("\t<td align=\"right\">\n");
      out.write("\t<p>");
      out.print( session.getAttribute("name") );
      out.write("さん、ようこそ</p>\n");
      out.write("\t<input type=\"submit\" value=\"ログアウト\">\n");
      out.write("\t</td>\n");
      out.write("\t</tr></table></form>\n");
      out.write("\t<form action=\"/cms/appmaster\" method=\"POST\">\n");
      out.write("\t<table border=\"0\">\n");
      out.write("\t<tr><td><p>更新後のデータを入力してください</p></td></tr>\n");
      out.write("\t<tr><td>主催団体<input type=\"text\" name=\"partyname\"></td></tr>\n");
      out.write("\t<tr><td>検定名<input type=\"text\" name=\"cername\"></td></tr>\n");
      out.write("\t<tr><td><input type=\"submit\" name=\"update\" value=\"更新\"></td></tr>\n");
      out.write("\t</table>\n");
      out.write("\t</form>\n");
      out.write("\t<a href = \"/cms/cms_man/mmain.jsp\">メインメニューへ戻る</a>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
